### PR TITLE
added Simplified Chinese translation; Apply the latest add-on template; Make add-ons settings panel translatable.

### PR DESCRIPTION
**Pull request by cary-rowen**
1. Updated the add-on template to 2022.1;
2. Added simplified Chinese translation;
3. Make the donation dialog to be translated;
4. Make the entries in the settings panel available for translation.

### CODE REVIEW

**Comment by cary-rowen** [comment]
@hamadatrichine 
Can you take a look at this?

**Comment by cary-rowen** [comment]
Subsequent work will include plugin template updates for 2022.1, making more strings translatable.

**Comment by hamadatrichine** [comment]
@cary-rowen Sorry for not noticing your PR before. Thank you for your contributions and I am perfectly fine with code that can improve the addon further. Translation work has been always the hardest thing to maintain because people submit some translations that maybe not up to date on the next release.

**Comment by cary-rowen** [comment]
Hi,
I edited the original description to match the changes I made, you can now review and decide if you want to merge this.
Thanks

**Pull request merged**
